screen -S context0 -X quit
screen -S context1 -X quit
screen -S context2 -X quit
screen -S context3 -X quit
screen -S context4 -X quit
screen -S context5 -X quit
screen -S context6 -X quit
screen -S context7 -X quit
screen -S context8 -X quit
screen -S context9 -X quit
screen -S context10 -X quit
screen -S context11 -X quit
screen -S context12 -X quit
screen -S context13 -X quit
screen -S context14 -X quit
screen -S context15 -X quit
screen -S context16 -X quit
screen -S context17 -X quit
screen -S context18 -X quit
screen -S context19 -X quit